### ISSUE TITLE
Journal Article- add author

### ISSUE THREAD

**Issue by ColinKhoury** [danipilze/aichi13#114]
Daniel please add (in order after John Wiersema)

Blanca León, PhD
Plant Resources Center
University of Texas at Austin
&
Department of Geography and the Environment
University of Texas at Austin

also the Crop Trust people all said Yes they want to be involved.

**Comment by danipilze** [comment]
great!
done

I put the word document here (it's private), One Drive have some latency issues but should see the changes now
https://cgiar-my.sharepoint.com/:w:/r/personal/d_amariles_cgiar_org/_layouts/15/WopiFrame.aspx?sourcedoc=%7BB4480A27-CEEE-43C3-A121-2FD784634B4C%7D&file=Aichi%2013%20journal%20article_2018_2_4.docx&action=default&IsList=1&ListId=%7B3DF0F837-39E6-4ED4-A19D-84F5DB42A3B9%7D&ListItemId=14215
