### ISSUE TITLE
look how many species has no native country

### ISSUE THREAD

**Issue by danipilze** [danipilze/aichi13#122]

**Comment by danipilze** [comment]
I should remember to do this

**Comment by ColinKhoury** [comment]
TO DO BEFORE RUNNING MAIN GROUP OF SPECIES

**Comment by danipilze** [comment]
@ColinKhoury These are the species ids with no native country
As you can see there are only 8
@stevensotelo @mariavictoriadiaz take them in count


> Taxon_key
> 2706438
> 5329860
> 2702817
> 3629084
> 5607179
> 4033932
> 6027150
> 6312389
>

**Comment by ColinKhoury** [comment]
Cool. with only 8, lets just delete them from the analysis
