### ISSUE TITLE
Review WDPA dataset to make sure we are using it correctly

### ISSUE THREAD

**Issue by ColinKhoury** [danipilze/aichi13#124]
Please review comments from BIP partners to our preliminary report and confirm about WDPA

**Comment by danipilze** [comment]
about WDPA we are using the latest published in 2017-12-22

**Comment by ColinKhoury** [comment]
TO DO BEFORE RUNNING MAIN GROUP OF SPECIES

**Comment by danipilze** [comment]
#126
