### ISSUE TITLE
Check "server1" counts file

### ISSUE THREAD

**Issue by ColinKhoury** [danipilze/aichi13#131]
The files that sits in "runs/species" have numbers that seem waaaay too big to be correct, eg.
2875979,575297,533589,3946,1209,571351,532380,337050,13610,224637
extremely rare to have a species with 575,000 points!!!!
it makes me wonder if there is some query error with number of records assigned to each species????? can you check asap Daniel? thanks

**Comment by danipilze** [comment]
I'm going to check
but i think it's possible since in GBIF there are 360,396 RESULTS https://www.gbif.org/occurrence/search?taxon_key=2875979
the others can come from the CWR dataset

**Comment by ColinKhoury** [comment]
Thanks for checking. This seems way too high to me. I think the biggest CWR species in our project might have had a few hundred thousand records, but not nearly that many with coordinates. As I looked at your list, it looked like many species had hundreds of thousands of coordinates. Intuitively something is wrong to me

**Comment by danipilze** [comment]
I deeply checked and it seems that 33% (170.348) of the useful records from that taxon comes from CWRDB.

Total useful records= 533589
Total useful without duplicates = 509675

![image](https://user-images.githubusercontent.com/3705866/38571166-6015e456-3cb5-11e8-91d8-740dd48b9602.png)

Just for the record, these are the top taxa with most useful records from the CWRDB, 19 of them has more than 100.000 useful records:

![image](https://user-images.githubusercontent.com/3705866/38571276-acd8f148-3cb5-11e8-8c6a-f0d251e4af11.png)

**Comment by ColinKhoury** [comment]
Thanks Daniel can you pull the names for me of the top 10 taxa?

**Comment by danipilze** [comment]
Sure Colin!
Take in count that with  the GBIF tool we merged different taxa at specie level.

e.i for `Elymus_repens_subsp._vallantianum` the query was 
`http://api.gbif.org/v1/species/match?kingdom=Plantae&name=Elymus_repens_subsp._vallantianum`
and we took always the `usageKey`

So I'll share you in groups, (here are names from both CWRDB and Genesys):


```
2706164	Holcus_lanatus	
2706164	Holcus lanatus	
2706164	Holcus lanatus L.	
```

```
5290299	Elymus_repens_f._heberhachis	
5290299	Elymus_repens_var._maritimum	
5290299	Elymus repens	
5290299	Elymus_repens_f._vulgare	
5290299	Elymus repens (L.) Gould repens	
5290299	Elymus_repens_var._leersianum	
5290299	Elymus_repens_subsp._vallantianum	
5290299	Elymus_repens_var._vulgare	
5290299	Elymus repens (L.) Gould	
5290299	Elymus_repens_var._maritima	
5290299	Elymus_repens_f._setiferum	
5290299	Elymus_repens_f._leersianum	
5290299	Elymus repens (L.) Gould elongatiformis (Drobow) Melderis	
5290299	Elymus_repens	
```

```
2875979	Corylus avellana 'heterophylla'	
2875979	Corylus avellana L. 'laciniata'	
2875979	Corylus avellana	
2875979	Corylus avellana L. 'purpurea'	
2875979	Corylus avellana L.	
2875979	Corylus_avellana	
2875979	Corylus avellana 'aurea'	
2875979	Corylus avellana 'contorta'	
2875979	Corylus avellana ~sp	
2875979	Corylus avellana 'variegata'	
2875979	Corylus avellana 'pendula'	
```

```
2975287	Vicia cracca L.
2975287	Vicia_cracca_subsp._tenuifolia
2975287	Vicia_cracca_f._albiflora
2975287	Vicia_cracca
2975287	Vicia_cracca_var._angustifolia
2975287	Vicia cracca
2975287	Vicia cracca L
```

```
7874143	Potentilla_erecta	
7874143	Potentilla erecta (L.) Räuschel	
7874143	Potentilla erecta (L.) R?uschel	
7874143	Potentilla erecta (L.)Raeusch.	
7874143	Potentilla erecta	
7874143	Potentilla erecta (L.)Räuschel	
7874143	Potentilla erecta (L.)R?uschel	
7874143	Potentilla erecta (L.) Raeusch	
7874143	Potentilla erecta L.	
7874143	Potentilla erecta (L.) Raeusch.	
```



```
5375388	Capsella bursa-pastoris (L.) Med.
5375388	Capsella bursa-pastoris
5375388	Capsella bursa-pastoris (L.)Medik.
5375388	Capsella bursa-pastoris (L.) Medik.
5375388	Capsella bursa-pastoris (L.) Medik. var. apetala
5375388	Capsella bursa-pastoris (L.)Med.
5375388	Capsella_bursa-pastoris
```

```
5366829	Potentilla anserina	
5366829	Potentilla_anserina	
5366829	Potentilla anserina L.	
5366869	Potentilla_anserina_subsp._pacifica	
```

```
3189870	Acer pseudoplatanus ~sp	
3189870	Acer pseudoplatanus L. 'leopoldii'	
3189870	Acer pseudoplatanus L. 'atropurpureum'	
3189870	Acer pseudoplatanus 'prinz andjery'	
3189870	Acer pseudoplatanus 'prinz handjeri'	
3189870	Acer pseudoplatanus L.	
3189870	Acer_pseudoplatanus	
3189870	Acer pseudoplatanus 'leopoldii'	
3189870	Acer pseudoplatanus L. 'purpureum'	
```

```
5290081	Alopecurus pratensis L.	
5290081	Alopecurus pratensis	
5290081	Alopecurus_pratensis	
```


```
3023221	Prunus spinosa	
3023221	Prunus_spinosa	
3023221	Prunus spinosa L.	
3023221	Prunus spinosa L	

```
