### ISSUE TITLE
Fix Namibia and South Sudan Isos for native areas and map display

### ISSUE THREAD

**Issue by ColinKhoury** [danipilze/aichi13#135]

**Comment by danipilze** [comment]
- [x] Namibia (fixed by @mariavictoriadiaz )
- [ ] South sudan (automate fixing)
- [ ] Add fake country "ZZ" with value=100 to keep absolute scale (see picture)


![image](https://user-images.githubusercontent.com/3705866/38819764-e91ec028-4161-11e8-8fcc-830a75b98840.png)
