### ISSUE TITLE
Place species with NO data into analysis

### ISSUE THREAD

**Issue by ColinKhoury** [danipilze/aichi13#136]
Add species without any data as 0 (high priority). make code

**Comment by jssotob** [comment]
After checking in detail, finally 305 species are no-data for modelling and GAP analysis (0 coordinates). Also, they are distributed into 169 countries. China is the one which contains the highest amount of species (118) and 46 countries contain just one species. Attached image shows the countries which contain more than 10 species with no-data. I will make a map to show this. 

![2018-04-12 10_58_36-native_areas_no_useful csv - excel](https://user-images.githubusercontent.com/25367136/38689241-b0a9c540-3e40-11e8-8b01-f7f9dd15288e.png)

**Comment by mariavictoriadiaz** [comment]
Species had already been included  into the analysis, at least, in the indicator step: Actually,  ers,grs, (insitu and exsitu) and srs are equal to zero in that cases (If total useful ocurrences= 0).

**Comment by ColinKhoury** [comment]
Great. Can you also confirm please that species with some data (H or G) but no coordinates ARE included in the analysis? In their case, only SRS will return a value different from 0

Thanks!

**Comment by danipilze** [comment]
yes, the records with no coordinates are also included in the count of total records

**Comment by jssotob** [comment]
Yes @ColinKhoury 

![image](https://user-images.githubusercontent.com/25367136/38704279-66aaffb0-3e6b-11e8-9813-8e99a0a48910.png)

This screenshot shows an example.

**Comment by ColinKhoury** [comment]
Super, thanks
