### ISSUE TITLE
generate priority categories vs richness chart

### ISSUE THREAD

**Issue by danipilze** [danipilze/aichi13#137]
- [x] generate the data in .JS, ordered by richness (@mariavictoriadiaz )
- [x] generate chart code (@danipilze)

![image](https://user-images.githubusercontent.com/3705866/38878080-c6262c36-4225-11e8-8435-cc1fbab96f5b.png)

**Comment by danipilze** [comment]
finally, it was made by regions to facilitate readability 
![image](https://user-images.githubusercontent.com/3705866/38954519-7778a076-4317-11e8-89e8-f2dff05b4da2.png)

**Comment by ColinKhoury** [comment]
interesting. probably better to sort by HP rather than richness
