### ISSUE TITLE
Bubble charts

### ISSUE THREAD

**Issue by danipilze** [danipilze/aichi13#138]
Export data for bubble charts

- [x] regions level
- [x] country level

![image](https://user-images.githubusercontent.com/3705866/38954575-9897ef14-4317-11e8-98ef-01bf10d7d66a.png)

**Comment by ColinKhoury** [comment]
What does the X axis mean?

**Comment by danipilze** [comment]
It is "Percentage of high priority species (%)" as suggested by @jramirezv

**Comment by jssotob** [comment]
yes, it is the proportion of species that are High Priority for each region, in comparison with Species Richness

**Comment by ColinKhoury** [comment]
Could you please put the final indicator number on X for me to see (I know its all low for all regions; scale appropriately)

**Comment by danipilze** [comment]
Sure!

- [x] make it for indicator score

**Comment by danipilze** [comment]
We have problems with Google charts to handle more than 100 records :disappointed:  in order to support the 228 countries :world_map: 

This how it should look,made with Power BI, lines in the middle are the average:

![image](https://user-images.githubusercontent.com/3705866/39055292-74ad5270-4479-11e8-86f7-1e94421c3a5d.png)
