### ISSUE TITLE
BIEN database for occurrence data?

### ISSUE THREAD

**Issue by ColinKhoury** [danipilze/aichi13#147]
http://bien.nceas.ucsb.edu/bien/biendata/

**Comment by ColinKhoury** [comment]
There's an R code for access
https://cran.r-project.org/web/packages/BIEN/index.html
https://github.com/bmaitner/RBIEN
http://bien.nceas.ucsb.edu/bien/tools/rbien/

**Comment by danipilze** [comment]
This is the check I made before https://github.com/CIAT-DAPA/aichi13/issues/33
I'm going to check again with the tools you shared

**Comment by danipilze** [comment]
I have tried several times and I have the same error, I guess it's because they made it a connection to a specific port of a database, which it's not a good practice and dangerous for them. Anyway, CIAT network may be blocking that, I'll investigate. 

```
> occurrence_counts<-BIEN_occurrence_records_per_species(species = "Coffea liberica")
Error in postgresqlNewConnection(drv, ...) : 
  RS-DBI driver: (could not connect public_bien@vegbiendev.nceas.ucsb.edu:5432 on dbname "public_vegbien": could not connect to server: Connection timed out (0x0000274C/10060)
	Is the server running on host "vegbiendev.nceas.ucsb.edu" (128.111.84.31) and accepting
	TCP/IP connections on port 5432?
```

**Comment by danipilze** [comment]
I asked IT to open the port, It seem it works outside CIAT's Network but not inside.
I'll let you know about this requirement.

**Comment by danipilze** [comment]
touching base with CIAT-IT again with comment on Ticket #27233

**Comment by danipilze** [comment]
ticket closed with CIAT-IT
package is working now

**Comment by luizecologia** [comment]
Can anyone help me to understand this error message? I'm trying to get trait data. Thanks.

Error in postgresqlNewConnection(drv, ...) : 
  RS-DBI driver: (could not connect public_bien@vegbiendev.nceas.ucsb.edu:5432 on dbname "public_vegbien": could not connect to server: Connection timed out (0x0000274C/10060)
	Is the server running on host "vegbiendev.nceas.ucsb.edu" (128.111.85.31) and accepting
	TCP/IP connections on port 5432?
)

**Comment by danipilze** [comment]
Dear @luizecologia please check if your firewall is not blocking the connection,
that worked for me. Connection at home was doing it right, but organizational restrictions didn't allow connect from office.

If you have further questions I suggest to directly contact the developers of  RBIEN https://github.com/bmaitner/RBIEN

this thread was only opened to register the incidence in our application.

**Comment by luizecologia** [comment]
Thanks @danipilze !
