### ISSUE TITLE
Change name of github and website

### ISSUE THREAD

**Issue by ColinKhoury** [danipilze/aichi13#152]
Hi we should make this accessible beyond Aichi as it is pertinent to other targets. 
Can we change git to something like
https://github.com/CIAT-DAPA/ConservationIndicator    ?
and website to something like 
https://ciat.cgiar.org/conservationindicator    ?

**Comment by danipilze** [comment]
Can I propose other options?:

- `CWR-Indicator`
- `UsefulPlants-Indicator`
- `ValuablePlants-Indicator`

**Comment by ColinKhoury** [comment]
Im ok with UsefulPlants-Indicator

**Comment by danipilze** [comment]
done
https://github.com/CIAT-DAPA/UsefulPlants-Indicator
https://ciat.cgiar.org/usefulplants-indicator/
