### ISSUE TITLE
calculate proportion of country-centroid records

### ISSUE THREAD

**Issue by danipilze** [danipilze/aichi13#155]

**Comment by danipilze** [comment]
![2018-08-20 12_50_52-centroids xlsx - excel](https://user-images.githubusercontent.com/3705866/44414366-353e7180-a533-11e8-8ba9-2c60ce0132b8.png)
 done form ADM 1 level, but we need to run again with for ADM 3 level

**Comment by ColinKhoury** [comment]
I understand this was done at country centroid level (ADM0); need to do at the ADM2 (county) level

**Comment by danipilze** [comment]
ok, thanks for correcting

**Comment by danipilze** [comment]
![image](https://user-images.githubusercontent.com/3705866/44593169-4e8c2b80-a788-11e8-8d4c-c4a354ef034f.png)
